//Generated by the protocol buffer compiler. DO NOT EDIT!
// source: portal.proto

package cz.jenda.tabor2022.data.proto

@kotlin.jvm.JvmName("-initializeplayerData")
inline fun playerData(block: PlayerDataKt.Dsl.() -> kotlin.Unit): cz.jenda.tabor2022.data.proto.Portal.PlayerData =
  PlayerDataKt.Dsl._create(cz.jenda.tabor2022.data.proto.Portal.PlayerData.newBuilder()).apply { block() }._build()
object PlayerDataKt {
  @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
  @com.google.protobuf.kotlin.ProtoDslMarker
  class Dsl private constructor(
    private val _builder: cz.jenda.tabor2022.data.proto.Portal.PlayerData.Builder
  ) {
    companion object {
      @kotlin.jvm.JvmSynthetic
      @kotlin.PublishedApi
      internal fun _create(builder: cz.jenda.tabor2022.data.proto.Portal.PlayerData.Builder): Dsl = Dsl(builder)
    }

    @kotlin.jvm.JvmSynthetic
    @kotlin.PublishedApi
    internal fun _build(): cz.jenda.tabor2022.data.proto.Portal.PlayerData = _builder.build()

    /**
     * <code>required string secret = 1;</code>
     */
    var secret: kotlin.String
      @JvmName("getSecret")
      get() = _builder.secret
      @JvmName("setSecret")
      set(value) {
          _builder.secret = value
      }
    /**
     * <code>required string secret = 1;</code>
     */
    fun clearSecret() {
      _builder.clearSecret()
    }
    /**
     * <code>required string secret = 1;</code>
     * @return Whether the secret field is set.
     */
    fun hasSecret(): kotlin.Boolean {
      return _builder.hasSecret()
    }

    /**
     * <code>required uint32 user_id = 2;</code>
     */
    var userId: kotlin.Int
      @JvmName("getUserId")
      get() = _builder.userId
      @JvmName("setUserId")
      set(value) {
          _builder.userId = value
      }
    /**
     * <code>required uint32 user_id = 2;</code>
     */
    fun clearUserId() {
      _builder.clearUserId()
    }
    /**
     * <code>required uint32 user_id = 2;</code>
     * @return Whether the userId field is set.
     */
    fun hasUserId(): kotlin.Boolean {
      return _builder.hasUserId()
    }

    /**
     * <code>required uint32 strength = 3;</code>
     */
    var strength: kotlin.Int
      @JvmName("getStrength")
      get() = _builder.strength
      @JvmName("setStrength")
      set(value) {
          _builder.strength = value
      }
    /**
     * <code>required uint32 strength = 3;</code>
     */
    fun clearStrength() {
      _builder.clearStrength()
    }
    /**
     * <code>required uint32 strength = 3;</code>
     * @return Whether the strength field is set.
     */
    fun hasStrength(): kotlin.Boolean {
      return _builder.hasStrength()
    }

    /**
     * <code>required uint32 magic = 4;</code>
     */
    var magic: kotlin.Int
      @JvmName("getMagic")
      get() = _builder.magic
      @JvmName("setMagic")
      set(value) {
          _builder.magic = value
      }
    /**
     * <code>required uint32 magic = 4;</code>
     */
    fun clearMagic() {
      _builder.clearMagic()
    }
    /**
     * <code>required uint32 magic = 4;</code>
     * @return Whether the magic field is set.
     */
    fun hasMagic(): kotlin.Boolean {
      return _builder.hasMagic()
    }

    /**
     * <code>required uint32 dexterity = 5;</code>
     */
    var dexterity: kotlin.Int
      @JvmName("getDexterity")
      get() = _builder.dexterity
      @JvmName("setDexterity")
      set(value) {
          _builder.dexterity = value
      }
    /**
     * <code>required uint32 dexterity = 5;</code>
     */
    fun clearDexterity() {
      _builder.clearDexterity()
    }
    /**
     * <code>required uint32 dexterity = 5;</code>
     * @return Whether the dexterity field is set.
     */
    fun hasDexterity(): kotlin.Boolean {
      return _builder.hasDexterity()
    }

    /**
     * <code>required uint32 bonus_points = 6;</code>
     */
    var bonusPoints: kotlin.Int
      @JvmName("getBonusPoints")
      get() = _builder.bonusPoints
      @JvmName("setBonusPoints")
      set(value) {
          _builder.bonusPoints = value
      }
    /**
     * <code>required uint32 bonus_points = 6;</code>
     */
    fun clearBonusPoints() {
      _builder.clearBonusPoints()
    }
    /**
     * <code>required uint32 bonus_points = 6;</code>
     * @return Whether the bonusPoints field is set.
     */
    fun hasBonusPoints(): kotlin.Boolean {
      return _builder.hasBonusPoints()
    }

    /**
     * An uninstantiable, behaviorless type to represent the field in
     * generics.
     */
    @kotlin.OptIn(com.google.protobuf.kotlin.OnlyForUseByGeneratedProtoCode::class)
    class SkillsProxy private constructor() : com.google.protobuf.kotlin.DslProxy()
    /**
     * <code>repeated .portal.Skill skills = 10;</code>
     */
    val skills: com.google.protobuf.kotlin.DslList<cz.jenda.tabor2022.data.proto.Portal.Skill, SkillsProxy>
      @kotlin.jvm.JvmSynthetic
      get() = com.google.protobuf.kotlin.DslList(
        _builder.skillsList
      )
    /**
     * <code>repeated .portal.Skill skills = 10;</code>
     * @param value The skills to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addSkills")
    fun com.google.protobuf.kotlin.DslList<cz.jenda.tabor2022.data.proto.Portal.Skill, SkillsProxy>.add(value: cz.jenda.tabor2022.data.proto.Portal.Skill) {
      _builder.addSkills(value)
    }/**
     * <code>repeated .portal.Skill skills = 10;</code>
     * @param value The skills to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignSkills")
    @Suppress("NOTHING_TO_INLINE")
    inline operator fun com.google.protobuf.kotlin.DslList<cz.jenda.tabor2022.data.proto.Portal.Skill, SkillsProxy>.plusAssign(value: cz.jenda.tabor2022.data.proto.Portal.Skill) {
      add(value)
    }/**
     * <code>repeated .portal.Skill skills = 10;</code>
     * @param values The skills to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("addAllSkills")
      fun com.google.protobuf.kotlin.DslList<cz.jenda.tabor2022.data.proto.Portal.Skill, SkillsProxy>.addAll(values: kotlin.collections.Iterable<cz.jenda.tabor2022.data.proto.Portal.Skill>) {
      _builder.addAllSkills(values)
    }/**
     * <code>repeated .portal.Skill skills = 10;</code>
     * @param values The skills to add.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("plusAssignAllSkills")
    @Suppress("NOTHING_TO_INLINE")
    inline operator fun com.google.protobuf.kotlin.DslList<cz.jenda.tabor2022.data.proto.Portal.Skill, SkillsProxy>.plusAssign(values: kotlin.collections.Iterable<cz.jenda.tabor2022.data.proto.Portal.Skill>) {
      addAll(values)
    }/**
     * <code>repeated .portal.Skill skills = 10;</code>
     * @param index The index to set the value at.
     * @param value The skills to set.
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("setSkills")
    operator fun com.google.protobuf.kotlin.DslList<cz.jenda.tabor2022.data.proto.Portal.Skill, SkillsProxy>.set(index: kotlin.Int, value: cz.jenda.tabor2022.data.proto.Portal.Skill) {
      _builder.setSkills(index, value)
    }/**
     * <code>repeated .portal.Skill skills = 10;</code>
     */
    @kotlin.jvm.JvmSynthetic
    @kotlin.jvm.JvmName("clearSkills")
      fun com.google.protobuf.kotlin.DslList<cz.jenda.tabor2022.data.proto.Portal.Skill, SkillsProxy>.clear() {
      _builder.clearSkills()
    }}
}
@kotlin.jvm.JvmSynthetic
inline fun cz.jenda.tabor2022.data.proto.Portal.PlayerData.copy(block: PlayerDataKt.Dsl.() -> kotlin.Unit): cz.jenda.tabor2022.data.proto.Portal.PlayerData =
  cz.jenda.tabor2022.data.proto.PlayerDataKt.Dsl._create(this.toBuilder()).apply { block() }._build()

