// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: portal.proto

package cz.jenda.tabor2022.data.proto;

public final class Portal {
  private Portal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code portal.Skill}
   */
  public enum Skill
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>Skill_Default = 0;</code>
     */
    Skill_Default(0),
    /**
     * <code>Skill_Climbing = 1;</code>
     */
    Skill_Climbing(1),
    /**
     * <code>Skill_LockPicking = 2;</code>
     */
    Skill_LockPicking(2),
    /**
     * <code>Magic_Fire = 101;</code>
     */
    Magic_Fire(101),
    ;

    /**
     * <code>Skill_Default = 0;</code>
     */
    public static final int Skill_Default_VALUE = 0;
    /**
     * <code>Skill_Climbing = 1;</code>
     */
    public static final int Skill_Climbing_VALUE = 1;
    /**
     * <code>Skill_LockPicking = 2;</code>
     */
    public static final int Skill_LockPicking_VALUE = 2;
    /**
     * <code>Magic_Fire = 101;</code>
     */
    public static final int Magic_Fire_VALUE = 101;


    public final int getNumber() {
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Skill valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Skill forNumber(int value) {
      switch (value) {
        case 0: return Skill_Default;
        case 1: return Skill_Climbing;
        case 2: return Skill_LockPicking;
        case 101: return Magic_Fire;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Skill>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Skill> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Skill>() {
            public Skill findValueByNumber(int number) {
              return Skill.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return cz.jenda.tabor2022.data.proto.Portal.getDescriptor().getEnumTypes().get(0);
    }

    private static final Skill[] VALUES = values();

    public static Skill valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    Skill(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:portal.Skill)
  }

  public interface PlayerDataOrBuilder extends
      // @@protoc_insertion_point(interface_extends:portal.PlayerData)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string secret = 1;</code>
     * @return Whether the secret field is set.
     */
    boolean hasSecret();
    /**
     * <code>required string secret = 1;</code>
     * @return The secret.
     */
    java.lang.String getSecret();
    /**
     * <code>required string secret = 1;</code>
     * @return The bytes for secret.
     */
    com.google.protobuf.ByteString
        getSecretBytes();

    /**
     * <code>required uint32 user_id = 2;</code>
     * @return Whether the userId field is set.
     */
    boolean hasUserId();
    /**
     * <code>required uint32 user_id = 2;</code>
     * @return The userId.
     */
    int getUserId();

    /**
     * <code>required uint32 strength = 3;</code>
     * @return Whether the strength field is set.
     */
    boolean hasStrength();
    /**
     * <code>required uint32 strength = 3;</code>
     * @return The strength.
     */
    int getStrength();

    /**
     * <code>required uint32 magic = 4;</code>
     * @return Whether the magic field is set.
     */
    boolean hasMagic();
    /**
     * <code>required uint32 magic = 4;</code>
     * @return The magic.
     */
    int getMagic();

    /**
     * <code>required uint32 dexterity = 5;</code>
     * @return Whether the dexterity field is set.
     */
    boolean hasDexterity();
    /**
     * <code>required uint32 dexterity = 5;</code>
     * @return The dexterity.
     */
    int getDexterity();

    /**
     * <code>required uint32 bonus_points = 6;</code>
     * @return Whether the bonusPoints field is set.
     */
    boolean hasBonusPoints();
    /**
     * <code>required uint32 bonus_points = 6;</code>
     * @return The bonusPoints.
     */
    int getBonusPoints();

    /**
     * <code>repeated .portal.Skill skills = 10;</code>
     * @return A list containing the skills.
     */
    java.util.List<cz.jenda.tabor2022.data.proto.Portal.Skill> getSkillsList();
    /**
     * <code>repeated .portal.Skill skills = 10;</code>
     * @return The count of skills.
     */
    int getSkillsCount();
    /**
     * <code>repeated .portal.Skill skills = 10;</code>
     * @param index The index of the element to return.
     * @return The skills at the given index.
     */
    cz.jenda.tabor2022.data.proto.Portal.Skill getSkills(int index);
  }
  /**
   * Protobuf type {@code portal.PlayerData}
   */
  public static final class PlayerData extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:portal.PlayerData)
      PlayerDataOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use PlayerData.newBuilder() to construct.
    private PlayerData(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private PlayerData() {
      secret_ = "";
      skills_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new PlayerData();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private PlayerData(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              secret_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              userId_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              strength_ = input.readUInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              magic_ = input.readUInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              dexterity_ = input.readUInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000020;
              bonusPoints_ = input.readUInt32();
              break;
            }
            case 80: {
              int rawValue = input.readEnum();
              @SuppressWarnings("deprecation")
              cz.jenda.tabor2022.data.proto.Portal.Skill value = cz.jenda.tabor2022.data.proto.Portal.Skill.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(10, rawValue);
              } else {
                if (!((mutable_bitField0_ & 0x00000040) != 0)) {
                  skills_ = new java.util.ArrayList<java.lang.Integer>();
                  mutable_bitField0_ |= 0x00000040;
                }
                skills_.add(rawValue);
              }
              break;
            }
            case 82: {
              int length = input.readRawVarint32();
              int oldLimit = input.pushLimit(length);
              while(input.getBytesUntilLimit() > 0) {
                int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
                cz.jenda.tabor2022.data.proto.Portal.Skill value = cz.jenda.tabor2022.data.proto.Portal.Skill.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(10, rawValue);
                } else {
                  if (!((mutable_bitField0_ & 0x00000040) != 0)) {
                    skills_ = new java.util.ArrayList<java.lang.Integer>();
                    mutable_bitField0_ |= 0x00000040;
                  }
                  skills_.add(rawValue);
                }
              }
              input.popLimit(oldLimit);
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000040) != 0)) {
          skills_ = java.util.Collections.unmodifiableList(skills_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cz.jenda.tabor2022.data.proto.Portal.internal_static_portal_PlayerData_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cz.jenda.tabor2022.data.proto.Portal.internal_static_portal_PlayerData_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cz.jenda.tabor2022.data.proto.Portal.PlayerData.class, cz.jenda.tabor2022.data.proto.Portal.PlayerData.Builder.class);
    }

    private int bitField0_;
    public static final int SECRET_FIELD_NUMBER = 1;
    private volatile java.lang.Object secret_;
    /**
     * <code>required string secret = 1;</code>
     * @return Whether the secret field is set.
     */
    @java.lang.Override
    public boolean hasSecret() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required string secret = 1;</code>
     * @return The secret.
     */
    @java.lang.Override
    public java.lang.String getSecret() {
      java.lang.Object ref = secret_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          secret_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string secret = 1;</code>
     * @return The bytes for secret.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getSecretBytes() {
      java.lang.Object ref = secret_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        secret_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USER_ID_FIELD_NUMBER = 2;
    private int userId_;
    /**
     * <code>required uint32 user_id = 2;</code>
     * @return Whether the userId field is set.
     */
    @java.lang.Override
    public boolean hasUserId() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required uint32 user_id = 2;</code>
     * @return The userId.
     */
    @java.lang.Override
    public int getUserId() {
      return userId_;
    }

    public static final int STRENGTH_FIELD_NUMBER = 3;
    private int strength_;
    /**
     * <code>required uint32 strength = 3;</code>
     * @return Whether the strength field is set.
     */
    @java.lang.Override
    public boolean hasStrength() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>required uint32 strength = 3;</code>
     * @return The strength.
     */
    @java.lang.Override
    public int getStrength() {
      return strength_;
    }

    public static final int MAGIC_FIELD_NUMBER = 4;
    private int magic_;
    /**
     * <code>required uint32 magic = 4;</code>
     * @return Whether the magic field is set.
     */
    @java.lang.Override
    public boolean hasMagic() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>required uint32 magic = 4;</code>
     * @return The magic.
     */
    @java.lang.Override
    public int getMagic() {
      return magic_;
    }

    public static final int DEXTERITY_FIELD_NUMBER = 5;
    private int dexterity_;
    /**
     * <code>required uint32 dexterity = 5;</code>
     * @return Whether the dexterity field is set.
     */
    @java.lang.Override
    public boolean hasDexterity() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>required uint32 dexterity = 5;</code>
     * @return The dexterity.
     */
    @java.lang.Override
    public int getDexterity() {
      return dexterity_;
    }

    public static final int BONUS_POINTS_FIELD_NUMBER = 6;
    private int bonusPoints_;
    /**
     * <code>required uint32 bonus_points = 6;</code>
     * @return Whether the bonusPoints field is set.
     */
    @java.lang.Override
    public boolean hasBonusPoints() {
      return ((bitField0_ & 0x00000020) != 0);
    }
    /**
     * <code>required uint32 bonus_points = 6;</code>
     * @return The bonusPoints.
     */
    @java.lang.Override
    public int getBonusPoints() {
      return bonusPoints_;
    }

    public static final int SKILLS_FIELD_NUMBER = 10;
    private java.util.List<java.lang.Integer> skills_;
    private static final com.google.protobuf.Internal.ListAdapter.Converter<
        java.lang.Integer, cz.jenda.tabor2022.data.proto.Portal.Skill> skills_converter_ =
            new com.google.protobuf.Internal.ListAdapter.Converter<
                java.lang.Integer, cz.jenda.tabor2022.data.proto.Portal.Skill>() {
              public cz.jenda.tabor2022.data.proto.Portal.Skill convert(java.lang.Integer from) {
                @SuppressWarnings("deprecation")
                cz.jenda.tabor2022.data.proto.Portal.Skill result = cz.jenda.tabor2022.data.proto.Portal.Skill.valueOf(from);
                return result == null ? cz.jenda.tabor2022.data.proto.Portal.Skill.Skill_Default : result;
              }
            };
    /**
     * <code>repeated .portal.Skill skills = 10;</code>
     * @return A list containing the skills.
     */
    @java.lang.Override
    public java.util.List<cz.jenda.tabor2022.data.proto.Portal.Skill> getSkillsList() {
      return new com.google.protobuf.Internal.ListAdapter<
          java.lang.Integer, cz.jenda.tabor2022.data.proto.Portal.Skill>(skills_, skills_converter_);
    }
    /**
     * <code>repeated .portal.Skill skills = 10;</code>
     * @return The count of skills.
     */
    @java.lang.Override
    public int getSkillsCount() {
      return skills_.size();
    }
    /**
     * <code>repeated .portal.Skill skills = 10;</code>
     * @param index The index of the element to return.
     * @return The skills at the given index.
     */
    @java.lang.Override
    public cz.jenda.tabor2022.data.proto.Portal.Skill getSkills(int index) {
      return skills_converter_.convert(skills_.get(index));
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasSecret()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStrength()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasMagic()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasDexterity()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBonusPoints()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, secret_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        output.writeUInt32(2, userId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        output.writeUInt32(3, strength_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        output.writeUInt32(4, magic_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        output.writeUInt32(5, dexterity_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        output.writeUInt32(6, bonusPoints_);
      }
      for (int i = 0; i < skills_.size(); i++) {
        output.writeEnum(10, skills_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, secret_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, userId_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(3, strength_);
      }
      if (((bitField0_ & 0x00000008) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, magic_);
      }
      if (((bitField0_ & 0x00000010) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(5, dexterity_);
      }
      if (((bitField0_ & 0x00000020) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(6, bonusPoints_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < skills_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeEnumSizeNoTag(skills_.get(i));
        }
        size += dataSize;
        size += 1 * skills_.size();
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof cz.jenda.tabor2022.data.proto.Portal.PlayerData)) {
        return super.equals(obj);
      }
      cz.jenda.tabor2022.data.proto.Portal.PlayerData other = (cz.jenda.tabor2022.data.proto.Portal.PlayerData) obj;

      if (hasSecret() != other.hasSecret()) return false;
      if (hasSecret()) {
        if (!getSecret()
            .equals(other.getSecret())) return false;
      }
      if (hasUserId() != other.hasUserId()) return false;
      if (hasUserId()) {
        if (getUserId()
            != other.getUserId()) return false;
      }
      if (hasStrength() != other.hasStrength()) return false;
      if (hasStrength()) {
        if (getStrength()
            != other.getStrength()) return false;
      }
      if (hasMagic() != other.hasMagic()) return false;
      if (hasMagic()) {
        if (getMagic()
            != other.getMagic()) return false;
      }
      if (hasDexterity() != other.hasDexterity()) return false;
      if (hasDexterity()) {
        if (getDexterity()
            != other.getDexterity()) return false;
      }
      if (hasBonusPoints() != other.hasBonusPoints()) return false;
      if (hasBonusPoints()) {
        if (getBonusPoints()
            != other.getBonusPoints()) return false;
      }
      if (!skills_.equals(other.skills_)) return false;
        return unknownFields.equals(other.unknownFields);
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSecret()) {
        hash = (37 * hash) + SECRET_FIELD_NUMBER;
        hash = (53 * hash) + getSecret().hashCode();
      }
      if (hasUserId()) {
        hash = (37 * hash) + USER_ID_FIELD_NUMBER;
        hash = (53 * hash) + getUserId();
      }
      if (hasStrength()) {
        hash = (37 * hash) + STRENGTH_FIELD_NUMBER;
        hash = (53 * hash) + getStrength();
      }
      if (hasMagic()) {
        hash = (37 * hash) + MAGIC_FIELD_NUMBER;
        hash = (53 * hash) + getMagic();
      }
      if (hasDexterity()) {
        hash = (37 * hash) + DEXTERITY_FIELD_NUMBER;
        hash = (53 * hash) + getDexterity();
      }
      if (hasBonusPoints()) {
        hash = (37 * hash) + BONUS_POINTS_FIELD_NUMBER;
        hash = (53 * hash) + getBonusPoints();
      }
      if (getSkillsCount() > 0) {
        hash = (37 * hash) + SKILLS_FIELD_NUMBER;
        hash = (53 * hash) + skills_.hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static cz.jenda.tabor2022.data.proto.Portal.PlayerData parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cz.jenda.tabor2022.data.proto.Portal.PlayerData parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cz.jenda.tabor2022.data.proto.Portal.PlayerData parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cz.jenda.tabor2022.data.proto.Portal.PlayerData parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cz.jenda.tabor2022.data.proto.Portal.PlayerData parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cz.jenda.tabor2022.data.proto.Portal.PlayerData parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cz.jenda.tabor2022.data.proto.Portal.PlayerData parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cz.jenda.tabor2022.data.proto.Portal.PlayerData parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static cz.jenda.tabor2022.data.proto.Portal.PlayerData parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static cz.jenda.tabor2022.data.proto.Portal.PlayerData parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static cz.jenda.tabor2022.data.proto.Portal.PlayerData parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static cz.jenda.tabor2022.data.proto.Portal.PlayerData parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(cz.jenda.tabor2022.data.proto.Portal.PlayerData prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code portal.PlayerData}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:portal.PlayerData)
        cz.jenda.tabor2022.data.proto.Portal.PlayerDataOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cz.jenda.tabor2022.data.proto.Portal.internal_static_portal_PlayerData_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cz.jenda.tabor2022.data.proto.Portal.internal_static_portal_PlayerData_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cz.jenda.tabor2022.data.proto.Portal.PlayerData.class, cz.jenda.tabor2022.data.proto.Portal.PlayerData.Builder.class);
      }

      // Construct using cz.jenda.tabor2022.data.proto.Portal.PlayerData.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        secret_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        userId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        strength_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        magic_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        dexterity_ = 0;
        bitField0_ = (bitField0_ & ~0x00000010);
        bonusPoints_ = 0;
        bitField0_ = (bitField0_ & ~0x00000020);
        skills_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cz.jenda.tabor2022.data.proto.Portal.internal_static_portal_PlayerData_descriptor;
      }

      @java.lang.Override
      public cz.jenda.tabor2022.data.proto.Portal.PlayerData getDefaultInstanceForType() {
        return cz.jenda.tabor2022.data.proto.Portal.PlayerData.getDefaultInstance();
      }

      @java.lang.Override
      public cz.jenda.tabor2022.data.proto.Portal.PlayerData build() {
        cz.jenda.tabor2022.data.proto.Portal.PlayerData result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public cz.jenda.tabor2022.data.proto.Portal.PlayerData buildPartial() {
        cz.jenda.tabor2022.data.proto.Portal.PlayerData result = new cz.jenda.tabor2022.data.proto.Portal.PlayerData(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          to_bitField0_ |= 0x00000001;
        }
        result.secret_ = secret_;
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.userId_ = userId_;
          to_bitField0_ |= 0x00000002;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.strength_ = strength_;
          to_bitField0_ |= 0x00000004;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.magic_ = magic_;
          to_bitField0_ |= 0x00000008;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          result.dexterity_ = dexterity_;
          to_bitField0_ |= 0x00000010;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          result.bonusPoints_ = bonusPoints_;
          to_bitField0_ |= 0x00000020;
        }
        if (((bitField0_ & 0x00000040) != 0)) {
          skills_ = java.util.Collections.unmodifiableList(skills_);
          bitField0_ = (bitField0_ & ~0x00000040);
        }
        result.skills_ = skills_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cz.jenda.tabor2022.data.proto.Portal.PlayerData) {
          return mergeFrom((cz.jenda.tabor2022.data.proto.Portal.PlayerData)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cz.jenda.tabor2022.data.proto.Portal.PlayerData other) {
        if (other == cz.jenda.tabor2022.data.proto.Portal.PlayerData.getDefaultInstance()) return this;
        if (other.hasSecret()) {
          bitField0_ |= 0x00000001;
          secret_ = other.secret_;
          onChanged();
        }
        if (other.hasUserId()) {
          setUserId(other.getUserId());
        }
        if (other.hasStrength()) {
          setStrength(other.getStrength());
        }
        if (other.hasMagic()) {
          setMagic(other.getMagic());
        }
        if (other.hasDexterity()) {
          setDexterity(other.getDexterity());
        }
        if (other.hasBonusPoints()) {
          setBonusPoints(other.getBonusPoints());
        }
        if (!other.skills_.isEmpty()) {
          if (skills_.isEmpty()) {
            skills_ = other.skills_;
            bitField0_ = (bitField0_ & ~0x00000040);
          } else {
            ensureSkillsIsMutable();
            skills_.addAll(other.skills_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasSecret()) {
          return false;
        }
        if (!hasUserId()) {
          return false;
        }
        if (!hasStrength()) {
          return false;
        }
        if (!hasMagic()) {
          return false;
        }
        if (!hasDexterity()) {
          return false;
        }
          return hasBonusPoints();
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cz.jenda.tabor2022.data.proto.Portal.PlayerData parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cz.jenda.tabor2022.data.proto.Portal.PlayerData) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object secret_ = "";
      /**
       * <code>required string secret = 1;</code>
       * @return Whether the secret field is set.
       */
      public boolean hasSecret() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required string secret = 1;</code>
       * @return The secret.
       */
      public java.lang.String getSecret() {
        java.lang.Object ref = secret_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            secret_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string secret = 1;</code>
       * @return The bytes for secret.
       */
      public com.google.protobuf.ByteString
          getSecretBytes() {
        java.lang.Object ref = secret_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          secret_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string secret = 1;</code>
       * @param value The secret to set.
       * @return This builder for chaining.
       */
      public Builder setSecret(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        secret_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string secret = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearSecret() {
        bitField0_ = (bitField0_ & ~0x00000001);
        secret_ = getDefaultInstance().getSecret();
        onChanged();
        return this;
      }
      /**
       * <code>required string secret = 1;</code>
       * @param value The bytes for secret to set.
       * @return This builder for chaining.
       */
      public Builder setSecretBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        secret_ = value;
        onChanged();
        return this;
      }

      private int userId_ ;
      /**
       * <code>required uint32 user_id = 2;</code>
       * @return Whether the userId field is set.
       */
      @java.lang.Override
      public boolean hasUserId() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required uint32 user_id = 2;</code>
       * @return The userId.
       */
      @java.lang.Override
      public int getUserId() {
        return userId_;
      }
      /**
       * <code>required uint32 user_id = 2;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(int value) {
        bitField0_ |= 0x00000002;
        userId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 user_id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userId_ = 0;
        onChanged();
        return this;
      }

      private int strength_ ;
      /**
       * <code>required uint32 strength = 3;</code>
       * @return Whether the strength field is set.
       */
      @java.lang.Override
      public boolean hasStrength() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>required uint32 strength = 3;</code>
       * @return The strength.
       */
      @java.lang.Override
      public int getStrength() {
        return strength_;
      }
      /**
       * <code>required uint32 strength = 3;</code>
       * @param value The strength to set.
       * @return This builder for chaining.
       */
      public Builder setStrength(int value) {
        bitField0_ |= 0x00000004;
        strength_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 strength = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearStrength() {
        bitField0_ = (bitField0_ & ~0x00000004);
        strength_ = 0;
        onChanged();
        return this;
      }

      private int magic_ ;
      /**
       * <code>required uint32 magic = 4;</code>
       * @return Whether the magic field is set.
       */
      @java.lang.Override
      public boolean hasMagic() {
        return ((bitField0_ & 0x00000008) != 0);
      }
      /**
       * <code>required uint32 magic = 4;</code>
       * @return The magic.
       */
      @java.lang.Override
      public int getMagic() {
        return magic_;
      }
      /**
       * <code>required uint32 magic = 4;</code>
       * @param value The magic to set.
       * @return This builder for chaining.
       */
      public Builder setMagic(int value) {
        bitField0_ |= 0x00000008;
        magic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 magic = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearMagic() {
        bitField0_ = (bitField0_ & ~0x00000008);
        magic_ = 0;
        onChanged();
        return this;
      }

      private int dexterity_ ;
      /**
       * <code>required uint32 dexterity = 5;</code>
       * @return Whether the dexterity field is set.
       */
      @java.lang.Override
      public boolean hasDexterity() {
        return ((bitField0_ & 0x00000010) != 0);
      }
      /**
       * <code>required uint32 dexterity = 5;</code>
       * @return The dexterity.
       */
      @java.lang.Override
      public int getDexterity() {
        return dexterity_;
      }
      /**
       * <code>required uint32 dexterity = 5;</code>
       * @param value The dexterity to set.
       * @return This builder for chaining.
       */
      public Builder setDexterity(int value) {
        bitField0_ |= 0x00000010;
        dexterity_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 dexterity = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearDexterity() {
        bitField0_ = (bitField0_ & ~0x00000010);
        dexterity_ = 0;
        onChanged();
        return this;
      }

      private int bonusPoints_ ;
      /**
       * <code>required uint32 bonus_points = 6;</code>
       * @return Whether the bonusPoints field is set.
       */
      @java.lang.Override
      public boolean hasBonusPoints() {
        return ((bitField0_ & 0x00000020) != 0);
      }
      /**
       * <code>required uint32 bonus_points = 6;</code>
       * @return The bonusPoints.
       */
      @java.lang.Override
      public int getBonusPoints() {
        return bonusPoints_;
      }
      /**
       * <code>required uint32 bonus_points = 6;</code>
       * @param value The bonusPoints to set.
       * @return This builder for chaining.
       */
      public Builder setBonusPoints(int value) {
        bitField0_ |= 0x00000020;
        bonusPoints_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 bonus_points = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearBonusPoints() {
        bitField0_ = (bitField0_ & ~0x00000020);
        bonusPoints_ = 0;
        onChanged();
        return this;
      }

      private java.util.List<java.lang.Integer> skills_ =
        java.util.Collections.emptyList();
      private void ensureSkillsIsMutable() {
        if (!((bitField0_ & 0x00000040) != 0)) {
          skills_ = new java.util.ArrayList<java.lang.Integer>(skills_);
          bitField0_ |= 0x00000040;
        }
      }
      /**
       * <code>repeated .portal.Skill skills = 10;</code>
       * @return A list containing the skills.
       */
      public java.util.List<cz.jenda.tabor2022.data.proto.Portal.Skill> getSkillsList() {
        return new com.google.protobuf.Internal.ListAdapter<
            java.lang.Integer, cz.jenda.tabor2022.data.proto.Portal.Skill>(skills_, skills_converter_);
      }
      /**
       * <code>repeated .portal.Skill skills = 10;</code>
       * @return The count of skills.
       */
      public int getSkillsCount() {
        return skills_.size();
      }
      /**
       * <code>repeated .portal.Skill skills = 10;</code>
       * @param index The index of the element to return.
       * @return The skills at the given index.
       */
      public cz.jenda.tabor2022.data.proto.Portal.Skill getSkills(int index) {
        return skills_converter_.convert(skills_.get(index));
      }
      /**
       * <code>repeated .portal.Skill skills = 10;</code>
       * @param index The index to set the value at.
       * @param value The skills to set.
       * @return This builder for chaining.
       */
      public Builder setSkills(
          int index, cz.jenda.tabor2022.data.proto.Portal.Skill value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSkillsIsMutable();
        skills_.set(index, value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .portal.Skill skills = 10;</code>
       * @param value The skills to add.
       * @return This builder for chaining.
       */
      public Builder addSkills(cz.jenda.tabor2022.data.proto.Portal.Skill value) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureSkillsIsMutable();
        skills_.add(value.getNumber());
        onChanged();
        return this;
      }
      /**
       * <code>repeated .portal.Skill skills = 10;</code>
       * @param values The skills to add.
       * @return This builder for chaining.
       */
      public Builder addAllSkills(
          java.lang.Iterable<? extends cz.jenda.tabor2022.data.proto.Portal.Skill> values) {
        ensureSkillsIsMutable();
        for (cz.jenda.tabor2022.data.proto.Portal.Skill value : values) {
          skills_.add(value.getNumber());
        }
        onChanged();
        return this;
      }
      /**
       * <code>repeated .portal.Skill skills = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearSkills() {
        skills_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:portal.PlayerData)
    }

    // @@protoc_insertion_point(class_scope:portal.PlayerData)
    private static final cz.jenda.tabor2022.data.proto.Portal.PlayerData DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new cz.jenda.tabor2022.data.proto.Portal.PlayerData();
    }

    public static cz.jenda.tabor2022.data.proto.Portal.PlayerData getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<PlayerData>
        PARSER = new com.google.protobuf.AbstractParser<PlayerData>() {
      @java.lang.Override
      public PlayerData parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PlayerData(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<PlayerData> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PlayerData> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public cz.jenda.tabor2022.data.proto.Portal.PlayerData getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_portal_PlayerData_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_portal_PlayerData_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014portal.proto\022\006portal\"\226\001\n\nPlayerData\022\016\n" +
      "\006secret\030\001 \002(\t\022\017\n\007user_id\030\002 \002(\r\022\020\n\010streng" +
      "th\030\003 \002(\r\022\r\n\005magic\030\004 \002(\r\022\021\n\tdexterity\030\005 \002" +
      "(\r\022\024\n\014bonus_points\030\006 \002(\r\022\035\n\006skills\030\n \003(\016" +
      "2\r.portal.Skill*U\n\005Skill\022\021\n\rSkill_Defaul" +
      "t\020\000\022\022\n\016Skill_Climbing\020\001\022\025\n\021Skill_LockPic" +
      "king\020\002\022\016\n\nMagic_Fire\020e"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_portal_PlayerData_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_portal_PlayerData_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_portal_PlayerData_descriptor,
        new java.lang.String[] { "Secret", "UserId", "Strength", "Magic", "Dexterity", "BonusPoints", "Skills", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
